"""
CryoFlux Lab - Efficiency Analysis Layer

This package provides tools for analyzing energy-to-learning efficiency (η = Δ/J)
from the receipts database generated by the CryoFlux orchestrator.

Components:
- metrics.py: Core metric computation functions
- report.py: CLI tool for generating efficiency reports
- plot_eta.py: Visualization tools for η time series
- update_task_stats.py: Offline aggregation script for task statistics
"""

__version__ = "0.1.0"
